/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_character = 1,
  anon_sym_PERCENT = 2,
  aux_sym_simple_expansion_token1 = 3,
  anon_sym_LBRACE = 4,
  aux_sym_expansion_token1 = 5,
  anon_sym_RBRACE = 6,
  aux_sym_padding_token1 = 7,
  aux_sym_padding_token2 = 8,
  sym_condition = 9,
  aux_sym_if_token1 = 10,
  anon_sym_QMARK = 11,
  anon_sym_AMP = 12,
  anon_sym_GT = 13,
  sym_pattern = 14,
  sym_variable = 15,
  sym_simple_expansion = 16,
  sym_expansion = 17,
  sym_padding = 18,
  sym_if = 19,
  aux_sym_pattern_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_character] = "character",
  [anon_sym_PERCENT] = "%",
  [aux_sym_simple_expansion_token1] = "simple_expansion_token1",
  [anon_sym_LBRACE] = "{",
  [aux_sym_expansion_token1] = "expansion_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym_padding_token1] = "padding_type",
  [aux_sym_padding_token2] = "padding_character",
  [sym_condition] = "condition",
  [aux_sym_if_token1] = "start_if",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AMP] = "&",
  [anon_sym_GT] = "end_if",
  [sym_pattern] = "pattern",
  [sym_variable] = "variable",
  [sym_simple_expansion] = "simple_expansion",
  [sym_expansion] = "expansion",
  [sym_padding] = "padding",
  [sym_if] = "if",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_character] = sym_character,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_simple_expansion_token1] = aux_sym_simple_expansion_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_expansion_token1] = aux_sym_expansion_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_padding_token1] = aux_sym_padding_token1,
  [aux_sym_padding_token2] = aux_sym_padding_token2,
  [sym_condition] = sym_condition,
  [aux_sym_if_token1] = aux_sym_if_token1,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT] = anon_sym_GT,
  [sym_pattern] = sym_pattern,
  [sym_variable] = sym_variable,
  [sym_simple_expansion] = sym_simple_expansion,
  [sym_expansion] = sym_expansion,
  [sym_padding] = sym_padding,
  [sym_if] = sym_if,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_simple_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_padding_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_padding_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_if_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_padding] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [5] = anon_sym_GT,
  },
  [2] = {
    [7] = anon_sym_GT,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 3,
  [9] = 9,
  [10] = 6,
  [11] = 2,
  [12] = 9,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 15,
  [22] = 14,
  [23] = 17,
  [24] = 16,
  [25] = 18,
  [26] = 19,
  [27] = 20,
  [28] = 20,
  [29] = 15,
  [30] = 18,
  [31] = 19,
  [32] = 17,
  [33] = 33,
  [34] = 16,
  [35] = 33,
  [36] = 33,
  [37] = 14,
  [38] = 38,
  [39] = 38,
  [40] = 38,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 44,
  [47] = 44,
  [48] = 43,
  [49] = 43,
  [50] = 50,
  [51] = 50,
  [52] = 50,
  [53] = 42,
  [54] = 42,
  [55] = 41,
  [56] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '%', 12,
        '&', 25,
        '<', 23,
        '>', 26,
        '?', 24,
        '{', 15,
        '}', 18,
        '*', 19,
        '|', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '&') ADVANCE(25);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '?') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '?') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(25);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '?') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '<' ||
          lookahead == '?') ADVANCE(23);
      if (lookahead == '*' ||
          lookahead == '>' ||
          lookahead == '|') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 6:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '&') ADVANCE(25);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '?') ADVANCE(24);
      if (lookahead == '}') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '{' &&
          lookahead != '|') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_padding_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_padding_token2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_condition);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_if_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_padding_token1] = ACTIONS(1),
    [aux_sym_if_token1] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_pattern] = STATE(45),
    [sym_variable] = STATE(11),
    [sym_simple_expansion] = STATE(37),
    [sym_expansion] = STATE(37),
    [sym_padding] = STATE(37),
    [sym_if] = STATE(37),
    [aux_sym_pattern_repeat1] = STATE(11),
    [sym_character] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_variable] = STATE(3),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(3),
    [sym_character] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_variable] = STATE(3),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(3),
    [sym_character] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(16),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_AMP] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(21), 1,
      sym_character,
    ACTIONS(23), 1,
      anon_sym_PERCENT,
    ACTIONS(11), 2,
      anon_sym_QMARK,
      anon_sym_GT,
    STATE(5), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(22), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [21] = 5,
    ACTIONS(25), 1,
      sym_character,
    ACTIONS(28), 1,
      anon_sym_PERCENT,
    ACTIONS(19), 2,
      anon_sym_QMARK,
      anon_sym_GT,
    STATE(5), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(22), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [42] = 5,
    ACTIONS(23), 1,
      anon_sym_PERCENT,
    ACTIONS(31), 1,
      sym_character,
    STATE(38), 1,
      sym_pattern,
    STATE(4), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(22), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [62] = 5,
    ACTIONS(23), 1,
      anon_sym_PERCENT,
    ACTIONS(31), 1,
      sym_character,
    STATE(39), 1,
      sym_pattern,
    STATE(4), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(22), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [82] = 5,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_character,
    ACTIONS(38), 1,
      anon_sym_PERCENT,
    STATE(8), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(37), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [102] = 5,
    ACTIONS(9), 1,
      anon_sym_PERCENT,
    ACTIONS(41), 1,
      sym_character,
    STATE(33), 1,
      sym_pattern,
    STATE(2), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(14), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [122] = 5,
    ACTIONS(23), 1,
      anon_sym_PERCENT,
    ACTIONS(31), 1,
      sym_character,
    STATE(40), 1,
      sym_pattern,
    STATE(4), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(22), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [142] = 5,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      sym_character,
    STATE(8), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(37), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [162] = 5,
    ACTIONS(9), 1,
      anon_sym_PERCENT,
    ACTIONS(41), 1,
      sym_character,
    STATE(35), 1,
      sym_pattern,
    STATE(2), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(14), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [182] = 5,
    ACTIONS(9), 1,
      anon_sym_PERCENT,
    ACTIONS(41), 1,
      sym_character,
    STATE(36), 1,
      sym_pattern,
    STATE(2), 2,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(14), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [202] = 1,
    ACTIONS(47), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [210] = 1,
    ACTIONS(49), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [218] = 1,
    ACTIONS(51), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [226] = 1,
    ACTIONS(53), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [234] = 1,
    ACTIONS(55), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [242] = 1,
    ACTIONS(57), 5,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [250] = 4,
    ACTIONS(59), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      aux_sym_padding_token1,
    ACTIONS(65), 1,
      aux_sym_if_token1,
  [263] = 1,
    ACTIONS(49), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [270] = 1,
    ACTIONS(47), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [277] = 1,
    ACTIONS(53), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [284] = 1,
    ACTIONS(51), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [291] = 1,
    ACTIONS(55), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [298] = 1,
    ACTIONS(57), 4,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [305] = 4,
    ACTIONS(67), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      aux_sym_padding_token1,
    ACTIONS(73), 1,
      aux_sym_if_token1,
  [318] = 4,
    ACTIONS(75), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(77), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      aux_sym_padding_token1,
    ACTIONS(81), 1,
      aux_sym_if_token1,
  [331] = 2,
    ACTIONS(49), 1,
      anon_sym_PERCENT,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_character,
  [339] = 2,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym_character,
  [347] = 2,
    ACTIONS(57), 1,
      anon_sym_PERCENT,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_character,
  [355] = 2,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_character,
  [363] = 2,
    ACTIONS(93), 1,
      anon_sym_AMP,
    ACTIONS(91), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [371] = 2,
    ACTIONS(51), 1,
      anon_sym_PERCENT,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_character,
  [379] = 2,
    ACTIONS(99), 1,
      anon_sym_AMP,
    ACTIONS(97), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [387] = 2,
    ACTIONS(103), 1,
      anon_sym_AMP,
    ACTIONS(101), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [395] = 2,
    ACTIONS(47), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_character,
  [403] = 1,
    ACTIONS(107), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [408] = 1,
    ACTIONS(109), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [413] = 1,
    ACTIONS(111), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [418] = 1,
    ACTIONS(113), 1,
      sym_condition,
  [422] = 1,
    ACTIONS(115), 1,
      anon_sym_QMARK,
  [426] = 1,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
  [430] = 1,
    ACTIONS(119), 1,
      aux_sym_padding_token2,
  [434] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
  [438] = 1,
    ACTIONS(123), 1,
      aux_sym_padding_token2,
  [442] = 1,
    ACTIONS(125), 1,
      aux_sym_padding_token2,
  [446] = 1,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
  [450] = 1,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
  [454] = 1,
    ACTIONS(131), 1,
      aux_sym_expansion_token1,
  [458] = 1,
    ACTIONS(133), 1,
      aux_sym_expansion_token1,
  [462] = 1,
    ACTIONS(135), 1,
      aux_sym_expansion_token1,
  [466] = 1,
    ACTIONS(137), 1,
      anon_sym_QMARK,
  [470] = 1,
    ACTIONS(139), 1,
      anon_sym_QMARK,
  [474] = 1,
    ACTIONS(141), 1,
      sym_condition,
  [478] = 1,
    ACTIONS(143), 1,
      sym_condition,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 62,
  [SMALL_STATE(8)] = 82,
  [SMALL_STATE(9)] = 102,
  [SMALL_STATE(10)] = 122,
  [SMALL_STATE(11)] = 142,
  [SMALL_STATE(12)] = 162,
  [SMALL_STATE(13)] = 182,
  [SMALL_STATE(14)] = 202,
  [SMALL_STATE(15)] = 210,
  [SMALL_STATE(16)] = 218,
  [SMALL_STATE(17)] = 226,
  [SMALL_STATE(18)] = 234,
  [SMALL_STATE(19)] = 242,
  [SMALL_STATE(20)] = 250,
  [SMALL_STATE(21)] = 263,
  [SMALL_STATE(22)] = 270,
  [SMALL_STATE(23)] = 277,
  [SMALL_STATE(24)] = 284,
  [SMALL_STATE(25)] = 291,
  [SMALL_STATE(26)] = 298,
  [SMALL_STATE(27)] = 305,
  [SMALL_STATE(28)] = 318,
  [SMALL_STATE(29)] = 331,
  [SMALL_STATE(30)] = 339,
  [SMALL_STATE(31)] = 347,
  [SMALL_STATE(32)] = 355,
  [SMALL_STATE(33)] = 363,
  [SMALL_STATE(34)] = 371,
  [SMALL_STATE(35)] = 379,
  [SMALL_STATE(36)] = 387,
  [SMALL_STATE(37)] = 395,
  [SMALL_STATE(38)] = 403,
  [SMALL_STATE(39)] = 408,
  [SMALL_STATE(40)] = 413,
  [SMALL_STATE(41)] = 418,
  [SMALL_STATE(42)] = 422,
  [SMALL_STATE(43)] = 426,
  [SMALL_STATE(44)] = 430,
  [SMALL_STATE(45)] = 434,
  [SMALL_STATE(46)] = 438,
  [SMALL_STATE(47)] = 442,
  [SMALL_STATE(48)] = 446,
  [SMALL_STATE(49)] = 450,
  [SMALL_STATE(50)] = 454,
  [SMALL_STATE(51)] = 458,
  [SMALL_STATE(52)] = 462,
  [SMALL_STATE(53)] = 466,
  [SMALL_STATE(54)] = 470,
  [SMALL_STATE(55)] = 474,
  [SMALL_STATE(56)] = 478,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_padding, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 6, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 8, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 8, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_padding, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_expando(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "expando",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
