/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_character = 1,
  anon_sym_PERCENT = 2,
  aux_sym_simple_expansion_token1 = 3,
  anon_sym_PERCENT_LBRACE = 4,
  aux_sym_expansion_token1 = 5,
  anon_sym_RBRACE = 6,
  anon_sym_PERCENT_STAR = 7,
  anon_sym_PERCENT_GT = 8,
  anon_sym_PERCENT_PIPE = 9,
  aux_sym_padding_token1 = 10,
  sym_condition = 11,
  anon_sym_PERCENT_LT = 12,
  anon_sym_PERCENT_QMARK = 13,
  anon_sym_QMARK = 14,
  anon_sym_AMP = 15,
  anon_sym_GT = 16,
  sym_pattern = 17,
  sym_variable = 18,
  sym_simple_expansion = 19,
  sym_expansion = 20,
  sym_padding = 21,
  sym_if = 22,
  aux_sym_pattern_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_character] = "character",
  [anon_sym_PERCENT] = "%",
  [aux_sym_simple_expansion_token1] = "simple_expansion_token1",
  [anon_sym_PERCENT_LBRACE] = "%{",
  [aux_sym_expansion_token1] = "expansion_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PERCENT_STAR] = "%*",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_PERCENT_PIPE] = "%|",
  [aux_sym_padding_token1] = "padding_token1",
  [sym_condition] = "condition",
  [anon_sym_PERCENT_LT] = "%<",
  [anon_sym_PERCENT_QMARK] = "%\?",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AMP] = "&",
  [anon_sym_GT] = ">",
  [sym_pattern] = "pattern",
  [sym_variable] = "variable",
  [sym_simple_expansion] = "simple_expansion",
  [sym_expansion] = "expansion",
  [sym_padding] = "padding",
  [sym_if] = "if",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_character] = sym_character,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_simple_expansion_token1] = aux_sym_simple_expansion_token1,
  [anon_sym_PERCENT_LBRACE] = anon_sym_PERCENT_LBRACE,
  [aux_sym_expansion_token1] = aux_sym_expansion_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PERCENT_STAR] = anon_sym_PERCENT_STAR,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_PERCENT_PIPE] = anon_sym_PERCENT_PIPE,
  [aux_sym_padding_token1] = aux_sym_padding_token1,
  [sym_condition] = sym_condition,
  [anon_sym_PERCENT_LT] = anon_sym_PERCENT_LT,
  [anon_sym_PERCENT_QMARK] = anon_sym_PERCENT_QMARK,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT] = anon_sym_GT,
  [sym_pattern] = sym_pattern,
  [sym_variable] = sym_variable,
  [sym_simple_expansion] = sym_simple_expansion,
  [sym_expansion] = sym_expansion,
  [sym_padding] = sym_padding,
  [sym_if] = sym_if,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_simple_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_padding_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_padding] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 2,
  [8] = 3,
  [9] = 9,
  [10] = 6,
  [11] = 9,
  [12] = 9,
  [13] = 6,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 15,
  [22] = 18,
  [23] = 19,
  [24] = 14,
  [25] = 17,
  [26] = 14,
  [27] = 19,
  [28] = 18,
  [29] = 16,
  [30] = 15,
  [31] = 17,
  [32] = 32,
  [33] = 32,
  [34] = 32,
  [35] = 35,
  [36] = 35,
  [37] = 35,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 38,
  [44] = 44,
  [45] = 44,
  [46] = 40,
  [47] = 47,
  [48] = 38,
  [49] = 49,
  [50] = 47,
  [51] = 47,
  [52] = 44,
  [53] = 41,
  [54] = 41,
  [55] = 39,
  [56] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(25);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 4:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '{' &&
          lookahead != '|') ADVANCE(11);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '%') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '>') ADVANCE(18);
      if (lookahead == '?') ADVANCE(24);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '|') ADVANCE(19);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '{' &&
          lookahead != '|') ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PERCENT_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PERCENT_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_padding_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_condition);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PERCENT_QMARK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PERCENT_STAR] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_PERCENT_PIPE] = ACTIONS(1),
    [anon_sym_PERCENT_LT] = ACTIONS(1),
    [anon_sym_PERCENT_QMARK] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_pattern] = STATE(49),
    [sym_variable] = STATE(7),
    [sym_simple_expansion] = STATE(26),
    [sym_expansion] = STATE(26),
    [sym_padding] = STATE(26),
    [sym_if] = STATE(26),
    [aux_sym_pattern_repeat1] = STATE(7),
    [sym_character] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(7),
    [anon_sym_PERCENT_STAR] = ACTIONS(9),
    [anon_sym_PERCENT_GT] = ACTIONS(9),
    [anon_sym_PERCENT_PIPE] = ACTIONS(9),
    [anon_sym_PERCENT_LT] = ACTIONS(11),
    [anon_sym_PERCENT_QMARK] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_variable] = STATE(3),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(3),
    [sym_character] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(17),
    [anon_sym_PERCENT_STAR] = ACTIONS(19),
    [anon_sym_PERCENT_GT] = ACTIONS(19),
    [anon_sym_PERCENT_PIPE] = ACTIONS(19),
    [anon_sym_PERCENT_LT] = ACTIONS(21),
    [anon_sym_PERCENT_QMARK] = ACTIONS(21),
    [anon_sym_QMARK] = ACTIONS(23),
    [anon_sym_AMP] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_variable] = STATE(3),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(3),
    [sym_character] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(28),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(31),
    [anon_sym_PERCENT_STAR] = ACTIONS(34),
    [anon_sym_PERCENT_GT] = ACTIONS(34),
    [anon_sym_PERCENT_PIPE] = ACTIONS(34),
    [anon_sym_PERCENT_LT] = ACTIONS(37),
    [anon_sym_PERCENT_QMARK] = ACTIONS(37),
    [anon_sym_QMARK] = ACTIONS(40),
    [anon_sym_AMP] = ACTIONS(40),
    [anon_sym_GT] = ACTIONS(40),
  },
  [STATE(4)] = {
    [sym_variable] = STATE(5),
    [sym_simple_expansion] = STATE(24),
    [sym_expansion] = STATE(24),
    [sym_padding] = STATE(24),
    [sym_if] = STATE(24),
    [aux_sym_pattern_repeat1] = STATE(5),
    [sym_character] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(44),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(46),
    [anon_sym_PERCENT_STAR] = ACTIONS(48),
    [anon_sym_PERCENT_GT] = ACTIONS(48),
    [anon_sym_PERCENT_PIPE] = ACTIONS(48),
    [anon_sym_PERCENT_LT] = ACTIONS(50),
    [anon_sym_PERCENT_QMARK] = ACTIONS(50),
    [anon_sym_QMARK] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym_variable] = STATE(5),
    [sym_simple_expansion] = STATE(24),
    [sym_expansion] = STATE(24),
    [sym_padding] = STATE(24),
    [sym_if] = STATE(24),
    [aux_sym_pattern_repeat1] = STATE(5),
    [sym_character] = ACTIONS(52),
    [anon_sym_PERCENT] = ACTIONS(55),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(58),
    [anon_sym_PERCENT_STAR] = ACTIONS(61),
    [anon_sym_PERCENT_GT] = ACTIONS(61),
    [anon_sym_PERCENT_PIPE] = ACTIONS(61),
    [anon_sym_PERCENT_LT] = ACTIONS(64),
    [anon_sym_PERCENT_QMARK] = ACTIONS(64),
    [anon_sym_QMARK] = ACTIONS(40),
    [anon_sym_GT] = ACTIONS(40),
  },
  [STATE(6)] = {
    [sym_pattern] = STATE(36),
    [sym_variable] = STATE(4),
    [sym_simple_expansion] = STATE(24),
    [sym_expansion] = STATE(24),
    [sym_padding] = STATE(24),
    [sym_if] = STATE(24),
    [aux_sym_pattern_repeat1] = STATE(4),
    [sym_character] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(44),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(46),
    [anon_sym_PERCENT_STAR] = ACTIONS(48),
    [anon_sym_PERCENT_GT] = ACTIONS(48),
    [anon_sym_PERCENT_PIPE] = ACTIONS(48),
    [anon_sym_PERCENT_LT] = ACTIONS(50),
    [anon_sym_PERCENT_QMARK] = ACTIONS(50),
  },
  [STATE(7)] = {
    [sym_variable] = STATE(8),
    [sym_simple_expansion] = STATE(26),
    [sym_expansion] = STATE(26),
    [sym_padding] = STATE(26),
    [sym_if] = STATE(26),
    [aux_sym_pattern_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_character] = ACTIONS(71),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(7),
    [anon_sym_PERCENT_STAR] = ACTIONS(9),
    [anon_sym_PERCENT_GT] = ACTIONS(9),
    [anon_sym_PERCENT_PIPE] = ACTIONS(9),
    [anon_sym_PERCENT_LT] = ACTIONS(11),
    [anon_sym_PERCENT_QMARK] = ACTIONS(11),
  },
  [STATE(8)] = {
    [sym_variable] = STATE(8),
    [sym_simple_expansion] = STATE(26),
    [sym_expansion] = STATE(26),
    [sym_padding] = STATE(26),
    [sym_if] = STATE(26),
    [aux_sym_pattern_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_character] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(78),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(81),
    [anon_sym_PERCENT_STAR] = ACTIONS(84),
    [anon_sym_PERCENT_GT] = ACTIONS(84),
    [anon_sym_PERCENT_PIPE] = ACTIONS(84),
    [anon_sym_PERCENT_LT] = ACTIONS(87),
    [anon_sym_PERCENT_QMARK] = ACTIONS(87),
  },
  [STATE(9)] = {
    [sym_pattern] = STATE(32),
    [sym_variable] = STATE(2),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(2),
    [sym_character] = ACTIONS(90),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(17),
    [anon_sym_PERCENT_STAR] = ACTIONS(19),
    [anon_sym_PERCENT_GT] = ACTIONS(19),
    [anon_sym_PERCENT_PIPE] = ACTIONS(19),
    [anon_sym_PERCENT_LT] = ACTIONS(21),
    [anon_sym_PERCENT_QMARK] = ACTIONS(21),
  },
  [STATE(10)] = {
    [sym_pattern] = STATE(35),
    [sym_variable] = STATE(4),
    [sym_simple_expansion] = STATE(24),
    [sym_expansion] = STATE(24),
    [sym_padding] = STATE(24),
    [sym_if] = STATE(24),
    [aux_sym_pattern_repeat1] = STATE(4),
    [sym_character] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(44),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(46),
    [anon_sym_PERCENT_STAR] = ACTIONS(48),
    [anon_sym_PERCENT_GT] = ACTIONS(48),
    [anon_sym_PERCENT_PIPE] = ACTIONS(48),
    [anon_sym_PERCENT_LT] = ACTIONS(50),
    [anon_sym_PERCENT_QMARK] = ACTIONS(50),
  },
  [STATE(11)] = {
    [sym_pattern] = STATE(34),
    [sym_variable] = STATE(2),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(2),
    [sym_character] = ACTIONS(90),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(17),
    [anon_sym_PERCENT_STAR] = ACTIONS(19),
    [anon_sym_PERCENT_GT] = ACTIONS(19),
    [anon_sym_PERCENT_PIPE] = ACTIONS(19),
    [anon_sym_PERCENT_LT] = ACTIONS(21),
    [anon_sym_PERCENT_QMARK] = ACTIONS(21),
  },
  [STATE(12)] = {
    [sym_pattern] = STATE(33),
    [sym_variable] = STATE(2),
    [sym_simple_expansion] = STATE(14),
    [sym_expansion] = STATE(14),
    [sym_padding] = STATE(14),
    [sym_if] = STATE(14),
    [aux_sym_pattern_repeat1] = STATE(2),
    [sym_character] = ACTIONS(90),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(17),
    [anon_sym_PERCENT_STAR] = ACTIONS(19),
    [anon_sym_PERCENT_GT] = ACTIONS(19),
    [anon_sym_PERCENT_PIPE] = ACTIONS(19),
    [anon_sym_PERCENT_LT] = ACTIONS(21),
    [anon_sym_PERCENT_QMARK] = ACTIONS(21),
  },
  [STATE(13)] = {
    [sym_pattern] = STATE(37),
    [sym_variable] = STATE(4),
    [sym_simple_expansion] = STATE(24),
    [sym_expansion] = STATE(24),
    [sym_padding] = STATE(24),
    [sym_if] = STATE(24),
    [aux_sym_pattern_repeat1] = STATE(4),
    [sym_character] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(44),
    [anon_sym_PERCENT_LBRACE] = ACTIONS(46),
    [anon_sym_PERCENT_STAR] = ACTIONS(48),
    [anon_sym_PERCENT_GT] = ACTIONS(48),
    [anon_sym_PERCENT_PIPE] = ACTIONS(48),
    [anon_sym_PERCENT_LT] = ACTIONS(50),
    [anon_sym_PERCENT_QMARK] = ACTIONS(50),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(92), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [14] = 1,
    ACTIONS(94), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [28] = 1,
    ACTIONS(96), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [42] = 1,
    ACTIONS(98), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [56] = 1,
    ACTIONS(100), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [70] = 1,
    ACTIONS(102), 11,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [84] = 1,
    ACTIONS(96), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [97] = 1,
    ACTIONS(94), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [110] = 1,
    ACTIONS(100), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [123] = 1,
    ACTIONS(102), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [136] = 1,
    ACTIONS(92), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [149] = 1,
    ACTIONS(98), 10,
      sym_character,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
      anon_sym_QMARK,
      anon_sym_GT,
  [162] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(92), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [176] = 2,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(102), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [190] = 2,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(100), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [204] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(96), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [218] = 2,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(94), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [232] = 2,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym_character,
    ACTIONS(98), 7,
      anon_sym_PERCENT,
      anon_sym_PERCENT_LBRACE,
      anon_sym_PERCENT_STAR,
      anon_sym_PERCENT_GT,
      anon_sym_PERCENT_PIPE,
      anon_sym_PERCENT_LT,
      anon_sym_PERCENT_QMARK,
  [246] = 2,
    ACTIONS(118), 1,
      anon_sym_AMP,
    ACTIONS(116), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [254] = 2,
    ACTIONS(122), 1,
      anon_sym_AMP,
    ACTIONS(120), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [262] = 2,
    ACTIONS(126), 1,
      anon_sym_AMP,
    ACTIONS(124), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [270] = 1,
    ACTIONS(128), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [275] = 1,
    ACTIONS(130), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [280] = 1,
    ACTIONS(132), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [285] = 1,
    ACTIONS(134), 1,
      aux_sym_padding_token1,
  [289] = 1,
    ACTIONS(136), 1,
      sym_condition,
  [293] = 1,
    ACTIONS(138), 1,
      aux_sym_simple_expansion_token1,
  [297] = 1,
    ACTIONS(140), 1,
      anon_sym_QMARK,
  [301] = 1,
    ACTIONS(142), 1,
      aux_sym_simple_expansion_token1,
  [305] = 1,
    ACTIONS(144), 1,
      aux_sym_padding_token1,
  [309] = 1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [313] = 1,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
  [317] = 1,
    ACTIONS(150), 1,
      aux_sym_simple_expansion_token1,
  [321] = 1,
    ACTIONS(152), 1,
      aux_sym_expansion_token1,
  [325] = 1,
    ACTIONS(154), 1,
      aux_sym_padding_token1,
  [329] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [333] = 1,
    ACTIONS(158), 1,
      aux_sym_expansion_token1,
  [337] = 1,
    ACTIONS(160), 1,
      aux_sym_expansion_token1,
  [341] = 1,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [345] = 1,
    ACTIONS(164), 1,
      anon_sym_QMARK,
  [349] = 1,
    ACTIONS(166), 1,
      anon_sym_QMARK,
  [353] = 1,
    ACTIONS(168), 1,
      sym_condition,
  [357] = 1,
    ACTIONS(170), 1,
      sym_condition,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 14,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 42,
  [SMALL_STATE(18)] = 56,
  [SMALL_STATE(19)] = 70,
  [SMALL_STATE(20)] = 84,
  [SMALL_STATE(21)] = 97,
  [SMALL_STATE(22)] = 110,
  [SMALL_STATE(23)] = 123,
  [SMALL_STATE(24)] = 136,
  [SMALL_STATE(25)] = 149,
  [SMALL_STATE(26)] = 162,
  [SMALL_STATE(27)] = 176,
  [SMALL_STATE(28)] = 190,
  [SMALL_STATE(29)] = 204,
  [SMALL_STATE(30)] = 218,
  [SMALL_STATE(31)] = 232,
  [SMALL_STATE(32)] = 246,
  [SMALL_STATE(33)] = 254,
  [SMALL_STATE(34)] = 262,
  [SMALL_STATE(35)] = 270,
  [SMALL_STATE(36)] = 275,
  [SMALL_STATE(37)] = 280,
  [SMALL_STATE(38)] = 285,
  [SMALL_STATE(39)] = 289,
  [SMALL_STATE(40)] = 293,
  [SMALL_STATE(41)] = 297,
  [SMALL_STATE(42)] = 301,
  [SMALL_STATE(43)] = 305,
  [SMALL_STATE(44)] = 309,
  [SMALL_STATE(45)] = 313,
  [SMALL_STATE(46)] = 317,
  [SMALL_STATE(47)] = 321,
  [SMALL_STATE(48)] = 325,
  [SMALL_STATE(49)] = 329,
  [SMALL_STATE(50)] = 333,
  [SMALL_STATE(51)] = 337,
  [SMALL_STATE(52)] = 341,
  [SMALL_STATE(53)] = 345,
  [SMALL_STATE(54)] = 349,
  [SMALL_STATE(55)] = 353,
  [SMALL_STATE(56)] = 357,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_padding, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 5, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 7, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 7, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_padding, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_expando(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "expando",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
