/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__character = 1,
  anon_sym_DOLLAR = 2,
  aux_sym_user_variable_token1 = 3,
  anon_sym_PERCENT = 4,
  aux_sym_simple_expansion_token1 = 5,
  anon_sym_LBRACE = 6,
  aux_sym_expansion_token1 = 7,
  anon_sym_RBRACE = 8,
  aux_sym_padding_token1 = 9,
  aux_sym_padding_token2 = 10,
  sym_condition = 11,
  aux_sym_if_token1 = 12,
  anon_sym_QMARK = 13,
  anon_sym_AMP = 14,
  anon_sym_GT = 15,
  sym_pattern = 16,
  sym_user_variable = 17,
  sym_variable = 18,
  sym_simple_expansion = 19,
  sym_expansion = 20,
  sym_padding = 21,
  sym_if = 22,
  aux_sym_pattern_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__character] = "_character",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_user_variable_token1] = "identifier",
  [anon_sym_PERCENT] = "%",
  [aux_sym_simple_expansion_token1] = "simple_expansion_token1",
  [anon_sym_LBRACE] = "{",
  [aux_sym_expansion_token1] = "expansion_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym_padding_token1] = "padding_type",
  [aux_sym_padding_token2] = "padding_character",
  [sym_condition] = "condition",
  [aux_sym_if_token1] = "start_if",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AMP] = "&",
  [anon_sym_GT] = "end_if",
  [sym_pattern] = "pattern",
  [sym_user_variable] = "user_variable",
  [sym_variable] = "variable",
  [sym_simple_expansion] = "simple_expansion",
  [sym_expansion] = "expansion",
  [sym_padding] = "padding",
  [sym_if] = "if",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__character] = sym__character,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_user_variable_token1] = aux_sym_user_variable_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_simple_expansion_token1] = aux_sym_simple_expansion_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_expansion_token1] = aux_sym_expansion_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_padding_token1] = aux_sym_padding_token1,
  [aux_sym_padding_token2] = aux_sym_padding_token2,
  [sym_condition] = sym_condition,
  [aux_sym_if_token1] = aux_sym_if_token1,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_GT] = anon_sym_GT,
  [sym_pattern] = sym_pattern,
  [sym_user_variable] = sym_user_variable,
  [sym_variable] = sym_variable,
  [sym_simple_expansion] = sym_simple_expansion,
  [sym_expansion] = sym_expansion,
  [sym_padding] = sym_padding,
  [sym_if] = sym_if,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__character] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_user_variable_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_simple_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_padding_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_padding_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_if_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_user_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_padding] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [5] = anon_sym_GT,
  },
  [2] = {
    [7] = anon_sym_GT,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 2,
  [10] = 8,
  [11] = 7,
  [12] = 8,
  [13] = 7,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 16,
  [22] = 17,
  [23] = 18,
  [24] = 14,
  [25] = 19,
  [26] = 15,
  [27] = 20,
  [28] = 15,
  [29] = 18,
  [30] = 20,
  [31] = 16,
  [32] = 17,
  [33] = 19,
  [34] = 34,
  [35] = 34,
  [36] = 34,
  [37] = 14,
  [38] = 38,
  [39] = 38,
  [40] = 38,
  [41] = 41,
  [42] = 41,
  [43] = 41,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 46,
  [48] = 48,
  [49] = 48,
  [50] = 44,
  [51] = 46,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 48,
  [56] = 52,
  [57] = 57,
  [58] = 44,
  [59] = 57,
  [60] = 57,
  [61] = 54,
  [62] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '$', 12,
        '%', 14,
        '&', 27,
        '<', 25,
        '>', 28,
        '?', 26,
        '{', 17,
        '}', 20,
        '*', 21,
        '|', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(12);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '&') ADVANCE(27);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '?') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(12);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '?') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(27);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '?') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '<' ||
          lookahead == '?') ADVANCE(25);
      if (lookahead == '*' ||
          lookahead == '>' ||
          lookahead == '|') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 6:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '$') ADVANCE(12);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '&') ADVANCE(27);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '?') ADVANCE(26);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '$') ADVANCE(12);
      if (lookahead == '%') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__character);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_user_variable_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_simple_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '{' &&
          lookahead != '|') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_padding_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_padding_token2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_condition);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead != 0 &&
          lookahead != '?' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_if_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_user_variable_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_padding_token1] = ACTIONS(1),
    [aux_sym_if_token1] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_pattern] = STATE(45),
    [sym_user_variable] = STATE(6),
    [sym_variable] = STATE(6),
    [sym_simple_expansion] = STATE(31),
    [sym_expansion] = STATE(31),
    [sym_padding] = STATE(31),
    [sym_if] = STATE(31),
    [aux_sym_pattern_repeat1] = STATE(6),
    [sym__character] = ACTIONS(3),
    [anon_sym_DOLLAR] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_user_variable] = STATE(2),
    [sym_variable] = STATE(2),
    [sym_simple_expansion] = STATE(16),
    [sym_expansion] = STATE(16),
    [sym_padding] = STATE(16),
    [sym_if] = STATE(16),
    [aux_sym_pattern_repeat1] = STATE(2),
    [sym__character] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(12),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_QMARK] = ACTIONS(18),
    [anon_sym_AMP] = ACTIONS(18),
    [anon_sym_GT] = ACTIONS(18),
  },
  [STATE(3)] = {
    [sym_user_variable] = STATE(2),
    [sym_variable] = STATE(2),
    [sym_simple_expansion] = STATE(16),
    [sym_expansion] = STATE(16),
    [sym_padding] = STATE(16),
    [sym_if] = STATE(16),
    [aux_sym_pattern_repeat1] = STATE(2),
    [sym__character] = ACTIONS(20),
    [anon_sym_DOLLAR] = ACTIONS(22),
    [anon_sym_PERCENT] = ACTIONS(24),
    [anon_sym_QMARK] = ACTIONS(26),
    [anon_sym_AMP] = ACTIONS(26),
    [anon_sym_GT] = ACTIONS(26),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(28), 1,
      sym__character,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    ACTIONS(34), 1,
      anon_sym_PERCENT,
    ACTIONS(18), 2,
      anon_sym_QMARK,
      anon_sym_GT,
    STATE(4), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(21), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [25] = 6,
    ACTIONS(37), 1,
      sym__character,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    ACTIONS(26), 2,
      anon_sym_QMARK,
      anon_sym_GT,
    STATE(4), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(21), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [50] = 6,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      sym__character,
    STATE(9), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(31), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [74] = 6,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    ACTIONS(47), 1,
      sym__character,
    STATE(41), 1,
      sym_pattern,
    STATE(5), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(21), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [98] = 6,
    ACTIONS(22), 1,
      anon_sym_DOLLAR,
    ACTIONS(24), 1,
      anon_sym_PERCENT,
    ACTIONS(49), 1,
      sym__character,
    STATE(38), 1,
      sym_pattern,
    STATE(3), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(16), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [122] = 6,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym__character,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(59), 1,
      anon_sym_PERCENT,
    STATE(9), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(31), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [146] = 6,
    ACTIONS(22), 1,
      anon_sym_DOLLAR,
    ACTIONS(24), 1,
      anon_sym_PERCENT,
    ACTIONS(49), 1,
      sym__character,
    STATE(39), 1,
      sym_pattern,
    STATE(3), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(16), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [170] = 6,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    ACTIONS(47), 1,
      sym__character,
    STATE(42), 1,
      sym_pattern,
    STATE(5), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(21), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [194] = 6,
    ACTIONS(22), 1,
      anon_sym_DOLLAR,
    ACTIONS(24), 1,
      anon_sym_PERCENT,
    ACTIONS(49), 1,
      sym__character,
    STATE(40), 1,
      sym_pattern,
    STATE(3), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(16), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [218] = 6,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    ACTIONS(47), 1,
      sym__character,
    STATE(43), 1,
      sym_pattern,
    STATE(5), 3,
      sym_user_variable,
      sym_variable,
      aux_sym_pattern_repeat1,
    STATE(21), 4,
      sym_simple_expansion,
      sym_expansion,
      sym_padding,
      sym_if,
  [242] = 1,
    ACTIONS(62), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [251] = 1,
    ACTIONS(64), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [260] = 1,
    ACTIONS(66), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [269] = 1,
    ACTIONS(68), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [278] = 1,
    ACTIONS(70), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [287] = 1,
    ACTIONS(72), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [296] = 1,
    ACTIONS(74), 6,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_GT,
  [305] = 1,
    ACTIONS(66), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [313] = 1,
    ACTIONS(68), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [321] = 1,
    ACTIONS(70), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [329] = 1,
    ACTIONS(62), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [337] = 1,
    ACTIONS(72), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [345] = 1,
    ACTIONS(64), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [353] = 1,
    ACTIONS(74), 5,
      sym__character,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_QMARK,
      anon_sym_GT,
  [361] = 2,
    ACTIONS(64), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym__character,
  [370] = 2,
    ACTIONS(70), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      sym__character,
  [379] = 2,
    ACTIONS(74), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym__character,
  [388] = 2,
    ACTIONS(66), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      sym__character,
  [397] = 2,
    ACTIONS(68), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym__character,
  [406] = 2,
    ACTIONS(72), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      sym__character,
  [415] = 4,
    ACTIONS(88), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      aux_sym_padding_token1,
    ACTIONS(94), 1,
      aux_sym_if_token1,
  [428] = 4,
    ACTIONS(96), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(98), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      aux_sym_padding_token1,
    ACTIONS(102), 1,
      aux_sym_if_token1,
  [441] = 4,
    ACTIONS(104), 1,
      aux_sym_simple_expansion_token1,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      aux_sym_padding_token1,
    ACTIONS(110), 1,
      aux_sym_if_token1,
  [454] = 2,
    ACTIONS(62), 2,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym__character,
  [463] = 2,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(114), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [471] = 2,
    ACTIONS(120), 1,
      anon_sym_AMP,
    ACTIONS(118), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [479] = 2,
    ACTIONS(124), 1,
      anon_sym_AMP,
    ACTIONS(122), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [487] = 1,
    ACTIONS(126), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [492] = 1,
    ACTIONS(128), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [497] = 1,
    ACTIONS(130), 2,
      anon_sym_QMARK,
      anon_sym_GT,
  [502] = 1,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
  [506] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [510] = 1,
    ACTIONS(136), 1,
      aux_sym_user_variable_token1,
  [514] = 1,
    ACTIONS(138), 1,
      aux_sym_user_variable_token1,
  [518] = 1,
    ACTIONS(140), 1,
      aux_sym_padding_token2,
  [522] = 1,
    ACTIONS(142), 1,
      aux_sym_padding_token2,
  [526] = 1,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
  [530] = 1,
    ACTIONS(146), 1,
      aux_sym_user_variable_token1,
  [534] = 1,
    ACTIONS(148), 1,
      aux_sym_expansion_token1,
  [538] = 1,
    ACTIONS(150), 1,
      aux_sym_expansion_token1,
  [542] = 1,
    ACTIONS(152), 1,
      sym_condition,
  [546] = 1,
    ACTIONS(154), 1,
      aux_sym_padding_token2,
  [550] = 1,
    ACTIONS(156), 1,
      aux_sym_expansion_token1,
  [554] = 1,
    ACTIONS(158), 1,
      anon_sym_QMARK,
  [558] = 1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [562] = 1,
    ACTIONS(162), 1,
      anon_sym_QMARK,
  [566] = 1,
    ACTIONS(164), 1,
      anon_sym_QMARK,
  [570] = 1,
    ACTIONS(166), 1,
      sym_condition,
  [574] = 1,
    ACTIONS(168), 1,
      sym_condition,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 25,
  [SMALL_STATE(6)] = 50,
  [SMALL_STATE(7)] = 74,
  [SMALL_STATE(8)] = 98,
  [SMALL_STATE(9)] = 122,
  [SMALL_STATE(10)] = 146,
  [SMALL_STATE(11)] = 170,
  [SMALL_STATE(12)] = 194,
  [SMALL_STATE(13)] = 218,
  [SMALL_STATE(14)] = 242,
  [SMALL_STATE(15)] = 251,
  [SMALL_STATE(16)] = 260,
  [SMALL_STATE(17)] = 269,
  [SMALL_STATE(18)] = 278,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 296,
  [SMALL_STATE(21)] = 305,
  [SMALL_STATE(22)] = 313,
  [SMALL_STATE(23)] = 321,
  [SMALL_STATE(24)] = 329,
  [SMALL_STATE(25)] = 337,
  [SMALL_STATE(26)] = 345,
  [SMALL_STATE(27)] = 353,
  [SMALL_STATE(28)] = 361,
  [SMALL_STATE(29)] = 370,
  [SMALL_STATE(30)] = 379,
  [SMALL_STATE(31)] = 388,
  [SMALL_STATE(32)] = 397,
  [SMALL_STATE(33)] = 406,
  [SMALL_STATE(34)] = 415,
  [SMALL_STATE(35)] = 428,
  [SMALL_STATE(36)] = 441,
  [SMALL_STATE(37)] = 454,
  [SMALL_STATE(38)] = 463,
  [SMALL_STATE(39)] = 471,
  [SMALL_STATE(40)] = 479,
  [SMALL_STATE(41)] = 487,
  [SMALL_STATE(42)] = 492,
  [SMALL_STATE(43)] = 497,
  [SMALL_STATE(44)] = 502,
  [SMALL_STATE(45)] = 506,
  [SMALL_STATE(46)] = 510,
  [SMALL_STATE(47)] = 514,
  [SMALL_STATE(48)] = 518,
  [SMALL_STATE(49)] = 522,
  [SMALL_STATE(50)] = 526,
  [SMALL_STATE(51)] = 530,
  [SMALL_STATE(52)] = 534,
  [SMALL_STATE(53)] = 538,
  [SMALL_STATE(54)] = 542,
  [SMALL_STATE(55)] = 546,
  [SMALL_STATE(56)] = 550,
  [SMALL_STATE(57)] = 554,
  [SMALL_STATE(58)] = 558,
  [SMALL_STATE(59)] = 562,
  [SMALL_STATE(60)] = 566,
  [SMALL_STATE(61)] = 570,
  [SMALL_STATE(62)] = 574,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [12] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [18] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_padding, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 6, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_user_variable, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 8, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_expansion, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 8, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_variable, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_padding, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [134] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_expando(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "expando",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
