---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli
          tree-sitter generate
      - name: Test
        run: |
          tree-sitter test
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: main
        run: |
          rm -rf main/src
          cp -r src main
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: main
          branch: main
          commit_message: 'chore: update generated artifacts'
          file_pattern: src
          add_options: -f

  npm:
    needs: test
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main

  crates:
    needs: test
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main

  pypi:
    needs: test
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
